class AsyncRunner
!!!70032567.java!!!	AsyncRunner(inout context : FilterContext, inout schedulerClass : Class)
        super(context);

        mSchedulerClass = schedulerClass;
        mLogVerbose = Log.isLoggable(TAG, Log.VERBOSE);
!!!70032695.java!!!	AsyncRunner(inout context : FilterContext)
        super(context);

        mSchedulerClass = SimpleScheduler.class;
        mLogVerbose = Log.isLoggable(TAG, Log.VERBOSE);
!!!70032823.java!!!	setDoneCallback(inout listener : GraphRunner::OnRunnerDoneListener) : void
        mDoneListener = listener;
!!!70032951.java!!!	setGraph(inout graph : FilterGraph) : void
        if (isRunning()) {
            throw new RuntimeException("Graph is already running!");
        }
        mRunner = new SyncRunner(mFilterContext, graph, mSchedulerClass);
!!!70033079.java!!!	getGraph() : FilterGraph
        return mRunner != null ? mRunner.getGraph() : null;
!!!70033207.java!!!	run() : void
        if (mLogVerbose) Log.v(TAG, "Running graph.");
        setException(null);

        if (isRunning()) {
            throw new RuntimeException("Graph is already running!");
        }
        if (mRunner == null) {
            throw new RuntimeException("Cannot run before a graph is set!");
        }
        mRunTask = this.new AsyncRunnerTask();

        setRunning(true);
        mRunTask.execute(mRunner);
!!!70033335.java!!!	stop() : void
        if (mRunTask != null && !mRunTask.isCancelled() ) {
            if (mLogVerbose) Log.v(TAG, "Stopping graph.");
            mRunTask.cancel(false);
        }
!!!70033463.java!!!	close() : void
        if (isRunning()) {
            throw new RuntimeException("Cannot close graph while it is running!");
        }
        if (mLogVerbose) Log.v(TAG, "Closing filters.");
        mRunner.close();
!!!70033591.java!!!	isRunning() : boolean
        return isProcessing;
!!!70033719.java!!!	getError() : Exception
        return mException;
!!!70033847.java!!!	setRunning(inout running : boolean) : void
        isProcessing = running;
!!!70033975.java!!!	setException(inout exception : Exception) : void
        mException = exception;
